@startuml ゲームループ

    
== Start ==

    Unity --> GameLoopManager : start()
    activate GameLoopManager

   
    GameLoopManager --> I_SceneObjectUpdatable :initObject
    deactivate GameLoopManager
    activate I_SceneObjectUpdatable
    I_SceneObjectUpdatable --> I_SceneObjectUpdatable : init GameObjects
    I_SceneObjectUpdatable --> GameLoopManager : return I_SceneLoadAlartable Object
    deactivate I_SceneObjectUpdatable
    activate GameLoopManager

    GameLoopManager --> I_SceneLoadAlartable : Observe
    deactivate GameLoopManager
    activate I_SceneLoadAlartable
    I_SceneLoadAlartable --> GameLoopManager
    deactivate I_SceneLoadAlartable
    activate GameLoopManager


    GameLoopManager --> Unity :return
    deactivate GameLoopManager

== Update ==

    Unity --> GameLoopManager : Update

    group UpdateLoop [case State Init]
        
        GameLoopManager --> I_SceneObjectUpdatable : startGame
        activate I_SceneObjectUpdatable
        I_SceneObjectUpdatable --> GameLoopManager
        deactivate I_SceneObjectUpdatable
        activate GameLoopManager
        GameLoopManager --> GameLoopManager : change State [Update]
        GameLoopManager --> Unity : return
        deactivate GameLoopManager 

    else case State Update
        GameLoopManager --> I_SceneObjectUpdatable : UpdateObject
        activate I_SceneObjectUpdatable
        group GameObject Update
            I_SceneObjectUpdatable --> I_SceneObjectUpdatable : GameObjects Update
            note over I_SceneObjectUpdatable : もしシーン変更が必要になったら
            I_SceneObjectUpdatable --> I_SceneLoadAlartable : SceneChange Alert
            deactivate I_SceneObjectUpdatable
            activate I_SceneLoadAlartable
            I_SceneLoadAlartable --> GameLoopManager : OnNext (通知)
            deactivate I_SceneLoadAlartable 
            
            GameLoopManager --> I_SceneLoadAlartable
            deactivate GameLoopManager
            activate I_SceneLoadAlartable
            I_SceneLoadAlartable --> I_SceneObjectUpdatable
            deactivate I_SceneLoadAlartable
            activate I_SceneObjectUpdatable
        end

        note over I_SceneObjectUpdatable : 各オブジェクト処理の終了を待つ
        I_SceneObjectUpdatable --> GameLoopManager
        deactivate I_SceneObjectUpdatable
        activate GameLoopManager
        note over GameLoopManager : シーン変更が必要なら
        GameLoopManager --> SceneLoader : LoadScene
        deactivate GameLoopManager
        activate SceneLoader
        group AsycLoad
            SceneLoader --> SceneLoader : LoadScene
        end
        
        SceneLoader --> GameLoopManager
        activate GameLoopManager
        GameLoopManager --> GameLoopManager : change State [Loading]
        GameLoopManager --> Unity : return
        deactivate GameLoopManager

    else case State Loading
        
        GameLoopManager --> GameLoopManager : Wait
        activate GameLoopManager
        GameLoopManager --> Unity : return
        deactivate GameLoopManager
    end

@enduml